<a href="https://colab.research.google.com/github/Teerawa-ctrl/Computer_Vision/blob/main/Lab01_blob_coloring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Region labeling

In [ ]:
import numpy as np

def blob_coloring_incremental(input_array):
    """
    ทำ Blob Coloring และเพิ่ม Counter เฉพาะเมื่อเจอเลข 1 ใน Binary Image
    :param input_array: ภาพ Binary 2D (ค่า 0 และ 1)
    :return: ภาพที่มี Label แต่ละ Blob พร้อมระบบนับ Counter
    """
    # ขนาดของภาพ
    rows, cols = input_array.shape

    # Output image สำหรับเก็บ label
    labeled_image = np.zeros_like(input_array, dtype=int)

    # Current counter
    counter = 1  # เริ่มต้นที่ 1
    equivalent_table = {}  # ตาราง Equivalent Table

    for i in range(rows):
        for j in range(cols):
            if input_array[i, j] == 1:  # หากเป็น Background (0)
                continue  # ไม่เปลี่ยนแปลงค่า Counter และ Label

            # Neighbor ด้านบนและด้านซ้าย
            neighbors = []
            if i > 0:  # ตรวจสอบด้านบน
                neighbors.append(labeled_image[i-1, j])
            if j > 0:  # ตรวจสอบด้านซ้าย
                neighbors.append(labeled_image[i, j-1])

            # กรอง neighbors ที่มี label (ไม่ใช่ 0)
            neighbors = [label for label in neighbors if label > 0]

            if not neighbors:  # หากไม่มี neighbor ใดที่มี label
                labeled_image[i, j] = counter
                equivalent_table[counter] = {counter}  # เพิ่มค่าใหม่ใน Equivalent Table
                print(f"New Counter: {counter}")
                counter += 1  # เพิ่ม Counter เมื่อเจอเลข 1
            else:
                # ใช้ Label ที่เล็กที่สุดจาก neighbors
                min_label = min(neighbors)
                labeled_image[i, j] = min_label

                # อัปเดต Equivalent Table
                for neighbor_label in neighbors:
                    equivalent_table[min_label] = equivalent_table[min_label].union(equivalent_table[neighbor_label])
                    equivalent_table[neighbor_label] = equivalent_table[min_label]

    print(f"Max Counter: {counter - 1}")  # แสดงค่า Counter สูงสุด
    print("\nEquivalent Table:")
    for label, eq_set in equivalent_table.items():
        print(f"Label {label}: {eq_set}")

    return labeled_image


# ตัวอย่างการใช้งาน
binary_image = np.array([
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 0],
    [1, 1, 0, 1, 1, 1],
    [1, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 1, 1],
    [0, 0, 0, 1, 1, 1]
])


labeled_image = blob_coloring_incremental(binary_image)

print("\nOriginal Binary Image:")
print(binary_image)

print("\nLabeled Image:")
print(labeled_image)


New Counter: 1
New Counter: 2
New Counter: 3
New Counter: 4
New Counter: 5
Max Counter: 5

Equivalent Table:
Label 1: {1}
Label 2: {2}
Label 3: {3, 4, 5}
Label 4: {3, 4, 5}
Label 5: {3, 4, 5}

Original Binary Image:
[[0 0 1 1 0 0]
 [0 0 1 1 1 0]
 [1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 1]
 [0 0 0 1 1 1]]

Labeled Image:
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 3 0 0 0]
 [0 4 3 3 3 0]
 [0 4 3 3 0 0]
 [5 4 3 0 0 0]]


# Line labeling

In [1]:
import numpy as np

def line_labeling(input_array):
    """
    ทำ Line Labeling โดยพิจารณา Neighbor: ซ้าย (Left), ซ้ายบน (Top-Left), บน (Top), บนขวา (Top-Right)
    :param input_array: ภาพ Binary 2D (ค่า 0 และ 1)
    :return: ภาพที่มี Label แต่ละ Line พร้อม Equivalent Table
    """
    # ขนาดของภาพ
    rows, cols = input_array.shape

    # Output image สำหรับเก็บ label
    labeled_image = np.zeros_like(input_array, dtype=int)

    # Current counter
    counter = 1  # เริ่มต้นที่ 1
    equivalent_table = {}  # ตาราง Equivalent Table

    for i in range(rows):
        for j in range(cols):
            if input_array[i, j] == 1:  # หากเป็น Background (0)
                continue  # ไม่เปลี่ยนแปลงค่า Counter และ Label

            # Neighbor: ซ้าย (Left), ซ้ายบน (Top-Left), บน (Top), บนขวา (Top-Right)
            neighbors = []
            if i > 0 and j > 0:  # ซ้ายบน (Top-Left)
                neighbors.append(labeled_image[i-1, j-1])
            if i > 0:  # บน (Top)
                neighbors.append(labeled_image[i-1, j])
            if i > 0 and j < cols-1:  # บนขวา (Top-Right)
                neighbors.append(labeled_image[i-1, j+1])
            if j > 0:  # ซ้าย (Left)
                neighbors.append(labeled_image[i, j-1])

            # กรอง neighbors ที่มี label (ไม่ใช่ 0)
            neighbors = [label for label in neighbors if label > 0]

            if not neighbors:  # หากไม่มี neighbor ใดที่มี label
                labeled_image[i, j] = counter
                equivalent_table[counter] = {counter}  # เพิ่มค่าใหม่ใน Equivalent Table
                print(f"New Counter: {counter}")
                counter += 1  # เพิ่ม Counter เมื่อเจอเลข 1
            else:
                # ใช้ Label ที่เล็กที่สุดจาก neighbors
                min_label = min(neighbors)
                labeled_image[i, j] = min_label

                # อัปเดต Equivalent Table
                for neighbor_label in neighbors:
                    equivalent_table[min_label] = equivalent_table[min_label].union(equivalent_table[neighbor_label])
                    equivalent_table[neighbor_label] = equivalent_table[min_label]

    print(f"Max Counter: {counter - 1}")  # แสดงค่า Counter สูงสุด
    print("\nEquivalent Table:")
    for label, eq_set in equivalent_table.items():
        print(f"Label {label}: {eq_set}")

    return labeled_image, equivalent_table


def resolve_equivalent_labels(labeled_image, equivalent_table):
    """
    ปรับปรุง Label ในภาพตาม Equivalent Table
    :param labeled_image: ภาพที่มี Label
    :param equivalent_table: ตาราง Equivalent Table
    :return: ภาพที่ปรับปรุง Label ตาม Equivalent Table
    """
    resolved_image = labeled_image.copy()

    # สร้าง Mapping ที่ลดความซับซ้อนของ Equivalent Table
    label_mapping = {}
    for label, eq_set in equivalent_table.items():
        root_label = min(eq_set)
        for eq_label in eq_set:
            label_mapping[eq_label] = root_label

    # ปรับ Label ในภาพ
    rows, cols = labeled_image.shape
    for i in range(rows):
        for j in range(cols):
            if resolved_image[i, j] > 0:
                resolved_image[i, j] = label_mapping[resolved_image[i, j]]

    # นับจำนวน Line
    unique_labels = set(np.unique(resolved_image)) - {0}  # เอาเฉพาะ Label ที่ไม่ใช่ 0
    print(f"\nDetected Objects: {len(unique_labels)}")

    return resolved_image


##ตัวอย่างการใช้งาน
binary_image = np.array([
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 0],
    [1, 1, 0, 1, 1, 1],
    [1, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 1, 1],
    [0, 0, 0, 1, 1, 1]
])

# ทำ Line Labeling
labeled_image, equivalent_table = line_labeling(binary_image)

print("\nOriginal Binary Image:")
print(binary_image)

print("\nLabeled Image (Before Resolving Equivalent Table):")
print(labeled_image)

# ปรับปรุง Label ตาม Equivalent Table
resolved_image = resolve_equivalent_labels(labeled_image, equivalent_table)

print("\nLabeled Image (After Resolving Equivalent Table):")
print(resolved_image)


New Counter: 1
New Counter: 2
Max Counter: 2

Equivalent Table:
Label 1: {1}
Label 2: {2}

Original Binary Image:
[[0 0 1 1 0 0]
 [0 0 1 1 1 0]
 [1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 1]
 [0 0 0 1 1 1]]

Labeled Image (Before Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 1 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 0 0]
 [1 1 1 0 0 0]]

Detected Objects: 2

Labeled Image (After Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 1 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 0 0]
 [1 1 1 0 0 0]]


# play ground

In [ ]:


# def blob_coloring_incremental(input_array):
#     """
#     ทำ Blob Coloring และเพิ่ม Counter เฉพาะเมื่อเจอเลข 1 ใน Binary Image
#     :param binary_image: ภาพ Binary 2D (ค่า 0 และ 1)
#     :return: ภาพที่มี Label แต่ละ Blob พร้อมระบบนับ Counter
#     """
#     # ขนาดของภาพ
#     rows, cols = input_array.shape

#     # Output image สำหรับเก็บ label
#     labeled_image = np.zeros_like(input_array, dtype=int)

#     # Current counter
#     counter = 1  # เริ่มต้นที่ 1

#     for i in range(rows):
#         for j in range(cols):
#             if input_array[i, j] == 1:  # หากเป็น Background (0)
#                 continue  # ไม่เปลี่ยนแปลงค่า Counter และ Label

#             # Neighbor ด้านบนและด้านซ้าย
#             neighbors = []
#             if i > 0:  # ตรวจสอบด้านบน
#                 neighbors.append(labeled_image[i-1, j])
#             if j > 0:  # ตรวจสอบด้านซ้าย
#                 neighbors.append(labeled_image[i, j-1])

#             # กรอง neighbors ที่มี label (ไม่ใช่ 0)
#             neighbors = [label for label in neighbors if label > 0]

#             if not neighbors:  # หากไม่มี neighbor ใดที่มี label
#                 labeled_image[i, j] = counter
#                 counter += 1  # เพิ่ม Counter เมื่อเจอเลข 1
#             else:
#                 # ใช้ Label ที่เล็กที่สุดจาก neighbors
#                 labeled_image[i, j] = min(neighbors)

#     return labeled_image


In [ ]:
# labeled_image = blob_coloring_incremental(input_array)

# print("Original Binary Image:")
# print(input_array)

# print("\nOutput Image:")
# print(labeled_image)

Original Binary Image:
[[0 0 1 1 0 0]
 [0 0 1 1 1 0]
 [1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 1]
 [0 0 0 1 1 1]]

Output Image:
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 3 0 0 0]
 [0 4 3 3 3 0]
 [0 4 3 3 0 0]
 [5 4 3 0 0 0]]


In [ ]:
# import numpy as np

# def blob_coloring_incremental(input_array):
#     """
#     ทำ Blob Coloring และเพิ่ม Counter เฉพาะเมื่อเจอเลข 1 ใน Binary Image
#     :param input_array: ภาพ Binary 2D (ค่า 0 และ 1)
#     :return: ภาพที่มี Label แต่ละ Blob พร้อมระบบนับ Counter
#     """
#     # ขนาดของภาพ
#     rows, cols = input_array.shape

#     # Output image สำหรับเก็บ label
#     labeled_image = np.zeros_like(input_array, dtype=int)

#     # Current counter
#     counter = 1  # เริ่มต้นที่ 1
#     equivalent_table = {}  # ตาราง Equivalent Table

#     for i in range(rows):
#         for j in range(cols):
#             if input_array[i, j] == 1:  # หากเป็น Background (0)
#                 continue  # ไม่เปลี่ยนแปลงค่า Counter และ Label

#             # Neighbor ด้านบนและด้านซ้าย
#             neighbors = []
#             if i > 0:  # ตรวจสอบด้านบน
#                 neighbors.append(labeled_image[i-1, j])
#             if j > 0:  # ตรวจสอบด้านซ้าย
#                 neighbors.append(labeled_image[i, j-1])

#             # กรอง neighbors ที่มี label (ไม่ใช่ 0)
#             neighbors = [label for label in neighbors if label > 0]

#             if not neighbors:  # หากไม่มี neighbor ใดที่มี label
#                 labeled_image[i, j] = counter
#                 equivalent_table[counter] = {counter}  # เพิ่มค่าใหม่ใน Equivalent Table
#                 print(f"New Counter: {counter}")
#                 counter += 1  # เพิ่ม Counter เมื่อเจอเลข 1
#             else:
#                 # ใช้ Label ที่เล็กที่สุดจาก neighbors
#                 min_label = min(neighbors)
#                 labeled_image[i, j] = min_label

#                 # อัปเดต Equivalent Table
#                 for neighbor_label in neighbors:
#                     equivalent_table[min_label] = equivalent_table[min_label].union(equivalent_table[neighbor_label])
#                     equivalent_table[neighbor_label] = equivalent_table[min_label]

#     print(f"Max Counter: {counter - 1}")  # แสดงค่า Counter สูงสุด
#     print("\nEquivalent Table:")
#     for label, eq_set in equivalent_table.items():
#         print(f"Label {label}: {eq_set}")

#     return labeled_image, equivalent_table


# def resolve_equivalent_labels(labeled_image, equivalent_table):
#     """
#     ปรับปรุง Label ในภาพตาม Equivalent Table
#     :param labeled_image: ภาพที่มี Label
#     :param equivalent_table: ตาราง Equivalent Table
#     :return: ภาพที่ปรับปรุง Label ตาม Equivalent Table
#     """
#     resolved_image = labeled_image.copy()

#     # สร้าง Mapping ที่ลดความซับซ้อนของ Equivalent Table
#     label_mapping = {}
#     for label, eq_set in equivalent_table.items():
#         root_label = min(eq_set)
#         for eq_label in eq_set:
#             label_mapping[eq_label] = root_label

#     # ปรับ Label ในภาพ
#     rows, cols = labeled_image.shape
#     for i in range(rows):
#         for j in range(cols):
#             if resolved_image[i, j] > 0:
#                 resolved_image[i, j] = label_mapping[resolved_image[i, j]]

#     # นับจำนวนวัตถุ
#     unique_labels = set(np.unique(resolved_image)) - {0}  # เอาเฉพาะ Label ที่ไม่ใช่ 0
#     print(f"\nDetected Objects: {len(unique_labels)}")

#     return resolved_image


# # ตัวอย่างการใช้งาน
# binary_image = np.array([
#     [0, 0, 1, 1, 0, 0],
#     [0, 0, 1, 1, 1, 0],
#     [1, 1, 0, 1, 1, 1],
#     [1, 0, 0, 0, 0, 1],
#     [1, 0, 0, 0, 1, 1],
#     [0, 0, 0, 1, 1, 1]
# ])

# # ทำ Blob Coloring
# labeled_image, equivalent_table = blob_coloring_incremental(binary_image)

# print("\nOriginal Binary Image:")
# print(binary_image)

# print("\nLabeled Image (Before Resolving Equivalent Table):")
# print(labeled_image)

# # ปรับปรุง Label ตาม Equivalent Table
# resolved_image = resolve_equivalent_labels(labeled_image, equivalent_table)

# print("\nLabeled Image (After Resolving Equivalent Table):")
# print(resolved_image)


New Counter: 1
New Counter: 2
New Counter: 3
New Counter: 4
New Counter: 5
Max Counter: 5

Equivalent Table:
Label 1: {1}
Label 2: {2}
Label 3: {3, 4, 5}
Label 4: {3, 4, 5}
Label 5: {3, 4, 5}

Original Binary Image:
[[0 0 1 1 0 0]
 [0 0 1 1 1 0]
 [1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 1]
 [0 0 0 1 1 1]]

Labeled Image (Before Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 3 0 0 0]
 [0 4 3 3 3 0]
 [0 4 3 3 0 0]
 [5 4 3 0 0 0]]

Detected Objects: 3

Labeled Image (After Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 3 0 0 0]
 [0 3 3 3 3 0]
 [0 3 3 3 0 0]
 [3 3 3 0 0 0]]


In [ ]:
# import numpy as np

# def line_labeling(input_array):
#     """
#     ทำ Line Labeling โดยพิจารณา Neighbor: ซ้าย (Left), ซ้ายบน (Top-Left), บน (Top), บนขวา (Top-Right)
#     :param input_array: ภาพ Binary 2D (ค่า 0 และ 1)
#     :return: ภาพที่มี Label แต่ละ Line พร้อม Equivalent Table
#     """
#     # ขนาดของภาพ
#     rows, cols = input_array.shape

#     # Output image สำหรับเก็บ label
#     labeled_image = np.zeros_like(input_array, dtype=int)

#     # Current counter
#     counter = 1  # เริ่มต้นที่ 1
#     equivalent_table = {}  # ตาราง Equivalent Table

#     for i in range(rows):
#         for j in range(cols):
#             if input_array[i, j] == 1:  # หากเป็น Background (0)
#                 continue  # ไม่เปลี่ยนแปลงค่า Counter และ Label

#             # Neighbor: ซ้าย (Left), ซ้ายบน (Top-Left), บน (Top), บนขวา (Top-Right)
#             neighbors = []
#             if i > 0 and j > 0:  # ซ้ายบน (Top-Left)
#                 neighbors.append(labeled_image[i-1, j-1])
#             if i > 0:  # บน (Top)
#                 neighbors.append(labeled_image[i-1, j])
#             if i > 0 and j < cols-1:  # บนขวา (Top-Right)
#                 neighbors.append(labeled_image[i-1, j+1])
#             if j > 0:  # ซ้าย (Left)
#                 neighbors.append(labeled_image[i, j-1])

#             # กรอง neighbors ที่มี label (ไม่ใช่ 0)
#             neighbors = [label for label in neighbors if label > 0]

#             if not neighbors:  # หากไม่มี neighbor ใดที่มี label
#                 labeled_image[i, j] = counter
#                 equivalent_table[counter] = {counter}  # เพิ่มค่าใหม่ใน Equivalent Table
#                 print(f"New Counter: {counter}")
#                 counter += 1  # เพิ่ม Counter เมื่อเจอเลข 1
#             else:
#                 # ใช้ Label ที่เล็กที่สุดจาก neighbors
#                 min_label = min(neighbors)
#                 labeled_image[i, j] = min_label

#                 # อัปเดต Equivalent Table
#                 for neighbor_label in neighbors:
#                     equivalent_table[min_label] = equivalent_table[min_label].union(equivalent_table[neighbor_label])
#                     equivalent_table[neighbor_label] = equivalent_table[min_label]

#     print(f"Max Counter: {counter - 1}")  # แสดงค่า Counter สูงสุด
#     print("\nEquivalent Table:")
#     for label, eq_set in equivalent_table.items():
#         print(f"Label {label}: {eq_set}")

#     return labeled_image, equivalent_table


# def resolve_equivalent_labels(labeled_image, equivalent_table):
#     """
#     ปรับปรุง Label ในภาพตาม Equivalent Table
#     :param labeled_image: ภาพที่มี Label
#     :param equivalent_table: ตาราง Equivalent Table
#     :return: ภาพที่ปรับปรุง Label ตาม Equivalent Table
#     """
#     resolved_image = labeled_image.copy()

#     # สร้าง Mapping ที่ลดความซับซ้อนของ Equivalent Table
#     label_mapping = {}
#     for label, eq_set in equivalent_table.items():
#         root_label = min(eq_set)
#         for eq_label in eq_set:
#             label_mapping[eq_label] = root_label

#     # ปรับ Label ในภาพ
#     rows, cols = labeled_image.shape
#     for i in range(rows):
#         for j in range(cols):
#             if resolved_image[i, j] > 0:
#                 resolved_image[i, j] = label_mapping[resolved_image[i, j]]

#     # นับจำนวน Line
#     unique_labels = set(np.unique(resolved_image)) - {0}  # เอาเฉพาะ Label ที่ไม่ใช่ 0
#     print(f"\nDetected Objects: {len(unique_labels)}")

#     return resolved_image


# ##ตัวอย่างการใช้งาน
# binary_image = np.array([
#     [0, 0, 1, 1, 0, 0],
#     [0, 0, 1, 1, 1, 0],
#     [1, 1, 0, 1, 1, 1],
#     [1, 0, 0, 0, 0, 1],
#     [1, 0, 0, 0, 1, 1],
#     [0, 0, 0, 1, 1, 1]
# ])

# # ทำ Line Labeling
# labeled_image, equivalent_table = line_labeling(binary_image)

# print("\nOriginal Binary Image:")
# print(binary_image)

# print("\nLabeled Image (Before Resolving Equivalent Table):")
# print(labeled_image)

# # ปรับปรุง Label ตาม Equivalent Table
# resolved_image = resolve_equivalent_labels(labeled_image, equivalent_table)

# print("\nLabeled Image (After Resolving Equivalent Table):")
# print(resolved_image)


New Counter: 1
New Counter: 2
Max Counter: 2

Equivalent Table:
Label 1: {1}
Label 2: {2}

Original Binary Image:
[[0 0 1 1 0 0]
 [0 0 1 1 1 0]
 [1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 1]
 [0 0 0 1 1 1]]

Labeled Image (Before Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 1 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 0 0]
 [1 1 1 0 0 0]]

Detected Objects: 2

Labeled Image (After Resolving Equivalent Table):
[[1 1 0 0 2 2]
 [1 1 0 0 0 2]
 [0 0 1 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 0 0]
 [1 1 1 0 0 0]]
